### ISSUE TITLE
Prepare the "Community Maintained" release

### ISSUE THREAD

**Issue by avivace** [gbadev-org/tonc#23]
- [x] https://github.com/gbadev-org/tonc/issues/16
- [x] https://github.com/gbadev-org/tonc/issues/1
- [x] Describe the past and the current status of the project (e.g. see the "[Foreword](https://gbdev.io/pandocs/)" on Pan Docs) https://github.com/gbadev-org/tonc/issues/1
- [x] Prepare an Authors/Contributors page, noting who helped writing new content/fix/improve it and who helped with the migration https://github.com/gbadev-org/tonc/issues/56
- [ ] #24 
- [ ] https://github.com/gbadev-org/libtonc-examples/issues/3
- [x] Add basic ci/cd
- [x] Port 90% of the content https://github.com/gbadev-org/tonc/issues/4
